baseURL: "https://zidan.xploit.my.id"
languageCode: "ind"
title: "XploIT"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
theme: hugo-theme-novela
    
paginate: 6

social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
  
taxonomies:
  author: authors
  
disqusShortname: XYW

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4
